/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class Simulation extends javax.swing.JFrame {

    /**
     * Creates new form Simulation
     */
    public Simulation() {
        initComponents();
    }
    
    public void exit(){
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        days_label = new javax.swing.JLabel();
        screen_warehouse_current_stock = new javax.swing.JLabel();
        pin_warehouse_current_stock = new javax.swing.JLabel();
        camera_warehouse_current_stock = new javax.swing.JLabel();
        button_warehouse_current_stock = new javax.swing.JLabel();
        button_warehouse_current_stock2 = new javax.swing.JLabel();
        button_warehouse_current_stock3 = new javax.swing.JLabel();
        button_warehouse_current_stock4 = new javax.swing.JLabel();
        phones_p = new javax.swing.JLabel();
        ganancias = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageCenter = new javax.swing.JTextArea();
        screen_producer_label = new javax.swing.JLabel();
        button_producer_label = new javax.swing.JLabel();
        number_camera_label = new javax.swing.JLabel();
        pin_producer_label = new javax.swing.JLabel();
        manager_status_label = new javax.swing.JLabel();
        boss_status_label = new javax.swing.JLabel();
        boss_wage = new javax.swing.JLabel();
        manager_wage = new javax.swing.JLabel();
        pin_expenses = new javax.swing.JLabel();
        screen_expenses = new javax.swing.JLabel();
        button_expenses = new javax.swing.JLabel();
        camera_expenses = new javax.swing.JLabel();
        pin_ammount = new javax.swing.JLabel();
        screen_ammount = new javax.swing.JLabel();
        button_ammount = new javax.swing.JLabel();
        camera_ammount = new javax.swing.JLabel();
        button_warehouse_current_stock1 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        days_label.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        days_label.setForeground(new java.awt.Color(255, 255, 255));
        days_label.setText("N/A");
        getContentPane().add(days_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, -1));

        screen_warehouse_current_stock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        screen_warehouse_current_stock.setForeground(new java.awt.Color(255, 255, 255));
        screen_warehouse_current_stock.setText("0");
        getContentPane().add(screen_warehouse_current_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 240, 24, -1));

        pin_warehouse_current_stock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pin_warehouse_current_stock.setForeground(new java.awt.Color(255, 255, 255));
        pin_warehouse_current_stock.setText("0");
        getContentPane().add(pin_warehouse_current_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 270, 24, -1));

        camera_warehouse_current_stock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        camera_warehouse_current_stock.setForeground(new java.awt.Color(255, 255, 255));
        camera_warehouse_current_stock.setText("0");
        getContentPane().add(camera_warehouse_current_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 300, 24, -1));

        button_warehouse_current_stock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_warehouse_current_stock.setForeground(new java.awt.Color(255, 255, 255));
        button_warehouse_current_stock.setText("0");
        getContentPane().add(button_warehouse_current_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 320, 24, -1));

        button_warehouse_current_stock2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_warehouse_current_stock2.setForeground(new java.awt.Color(255, 255, 255));
        button_warehouse_current_stock2.setText("0");
        getContentPane().add(button_warehouse_current_stock2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 380, 24, -1));

        button_warehouse_current_stock3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_warehouse_current_stock3.setForeground(new java.awt.Color(255, 255, 255));
        button_warehouse_current_stock3.setText("0");
        getContentPane().add(button_warehouse_current_stock3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, 24, -1));

        button_warehouse_current_stock4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_warehouse_current_stock4.setForeground(new java.awt.Color(255, 255, 255));
        button_warehouse_current_stock4.setText("0");
        getContentPane().add(button_warehouse_current_stock4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 420, 24, -1));

        phones_p.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        phones_p.setForeground(new java.awt.Color(255, 255, 255));
        phones_p.setText("0");
        getContentPane().add(phones_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 560, -1, -1));

        ganancias.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ganancias.setForeground(new java.awt.Color(255, 255, 255));
        ganancias.setText("0");
        getContentPane().add(ganancias, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 630, -1, -1));

        messageCenter.setColumns(20);
        messageCenter.setRows(5);
        jScrollPane1.setViewportView(messageCenter);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 700, 430, 60));

        screen_producer_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        screen_producer_label.setForeground(new java.awt.Color(255, 255, 255));
        screen_producer_label.setText("N/A");
        getContentPane().add(screen_producer_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        button_producer_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_producer_label.setForeground(new java.awt.Color(255, 255, 255));
        button_producer_label.setText("N/A");
        getContentPane().add(button_producer_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, -1, -1));

        number_camera_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        number_camera_label.setForeground(new java.awt.Color(255, 255, 255));
        number_camera_label.setText("N/A");
        getContentPane().add(number_camera_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        pin_producer_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pin_producer_label.setForeground(new java.awt.Color(255, 255, 255));
        pin_producer_label.setText("N/A");
        getContentPane().add(pin_producer_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        manager_status_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manager_status_label.setForeground(new java.awt.Color(255, 255, 255));
        manager_status_label.setText("N/A");
        getContentPane().add(manager_status_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        boss_status_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boss_status_label.setForeground(new java.awt.Color(255, 255, 255));
        boss_status_label.setText("N/A");
        getContentPane().add(boss_status_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, -1, -1));

        boss_wage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boss_wage.setForeground(new java.awt.Color(255, 255, 255));
        boss_wage.setText("N/A");
        getContentPane().add(boss_wage, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 740, -1, -1));

        manager_wage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manager_wage.setForeground(new java.awt.Color(255, 255, 255));
        manager_wage.setText("N/A");
        getContentPane().add(manager_wage, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 760, -1, -1));

        pin_expenses.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pin_expenses.setForeground(new java.awt.Color(255, 255, 255));
        pin_expenses.setText("0");
        getContentPane().add(pin_expenses, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 600, 17, -1));

        screen_expenses.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        screen_expenses.setForeground(new java.awt.Color(255, 255, 255));
        screen_expenses.setText("0");
        getContentPane().add(screen_expenses, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 620, 17, -1));

        button_expenses.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_expenses.setForeground(new java.awt.Color(255, 255, 255));
        button_expenses.setText("0");
        getContentPane().add(button_expenses, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 650, 17, -1));

        camera_expenses.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        camera_expenses.setForeground(new java.awt.Color(255, 255, 255));
        camera_expenses.setText("0");
        getContentPane().add(camera_expenses, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 670, 17, -1));

        pin_ammount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pin_ammount.setForeground(new java.awt.Color(255, 255, 255));
        pin_ammount.setText("0");
        getContentPane().add(pin_ammount, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, 26, -1));

        screen_ammount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        screen_ammount.setForeground(new java.awt.Color(255, 255, 255));
        screen_ammount.setText("0");
        getContentPane().add(screen_ammount, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 640, 26, -1));

        button_ammount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_ammount.setForeground(new java.awt.Color(255, 255, 255));
        button_ammount.setText("0");
        getContentPane().add(button_ammount, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 670, 26, -1));

        camera_ammount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        camera_ammount.setForeground(new java.awt.Color(255, 255, 255));
        camera_ammount.setText("0");
        getContentPane().add(camera_ammount, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 700, 26, -1));

        button_warehouse_current_stock1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_warehouse_current_stock1.setForeground(new java.awt.Color(255, 255, 255));
        button_warehouse_current_stock1.setText("0");
        getContentPane().add(button_warehouse_current_stock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 350, 20, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\fdsfds1.jpg")); // NOI18N
        jLabel32.setText("0");
        jLabel32.setToolTipText("");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -60, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulation().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel boss_status_label;
    public javax.swing.JLabel boss_wage;
    public javax.swing.JLabel button_ammount;
    public javax.swing.JLabel button_expenses;
    public javax.swing.JLabel button_producer_label;
    public javax.swing.JLabel button_warehouse_current_stock;
    public javax.swing.JLabel button_warehouse_current_stock1;
    public javax.swing.JLabel button_warehouse_current_stock2;
    public javax.swing.JLabel button_warehouse_current_stock3;
    public javax.swing.JLabel button_warehouse_current_stock4;
    public javax.swing.JLabel camera_ammount;
    public javax.swing.JLabel camera_expenses;
    public javax.swing.JLabel camera_warehouse_current_stock;
    public javax.swing.JLabel days_label;
    public javax.swing.JLabel ganancias;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    public javax.swing.JLabel manager_status_label;
    public javax.swing.JLabel manager_wage;
    public javax.swing.JTextArea messageCenter;
    public javax.swing.JLabel number_camera_label;
    public javax.swing.JLabel phones_p;
    public javax.swing.JLabel pin_ammount;
    public javax.swing.JLabel pin_expenses;
    public javax.swing.JLabel pin_producer_label;
    public javax.swing.JLabel pin_warehouse_current_stock;
    public javax.swing.JLabel screen_ammount;
    public javax.swing.JLabel screen_expenses;
    public javax.swing.JLabel screen_producer_label;
    public javax.swing.JLabel screen_warehouse_current_stock;
    // End of variables declaration//GEN-END:variables

    
    public void jLabelBoss(String text){
        manager_status_label.setText(text);
    }

}
